apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "student-management.fullname" . }}
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"